import 'package:flutter/material.dart';

class HomePageTemp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Homa page temporal'),
      ),
        body: ListView(
          children: <Widget>[
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text(':V'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text(':V'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text(':V'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text(':V'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text(':V'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text(':V'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text(':V'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text(':V'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
            Text('hola mundo'),
          ],
      ),
    );
  }
}